### ISSUE TITLE
Layouts etc

### ISSUE THREAD

**Issue by lawrennd** [aistats/aistats2021#2]
Hi @robert-giaquinto , I noticed a few changes to the primary layouts which I've reverted, some explanations below. Hope that's all OK!

For consistency across different years, I'd like to keep the structure of the pages each year the same. That's the reason for adding in the remote theme. It means we can keep good archived records of the conference and (I hope) eventually be able to credit properly the people who've contributed to the conference.

I've reverted index.html back to the 'home layout'. I noticed the main change was putting tentatively in for this year's conference. To do that I've added a file _includes/conference-description.html which overwrites the remote/theme version  of that file adding in 'tentatively'. 

I've also reinstated edit links. They are purposefully left to encourage people in the community to make changes to information that pertains to them. I know it's less relevant for the front page, but it actually makes it convenient for you to make direct changes to information there. This is something I started with PMLR several years ago, and it seems to work well. 

Any problems let me know, basic message is if we need to look at the layout, let's discuss, because that's a cross year thing and changes will be wrapped back into the remote theme so that everyone (and other conferences) benefit. But any content changes you need to make, go ahead and add or edit files. 

Apologies for being picky, but there are now a bunch of pages sitting on this remote/theme and it was a lot of work to get them consistent so that they can be managed together, so I'm naturally alert to divergences from the template.

**Comment by robert-giaquinto** [comment]
This is great, thank you!

For index.html, that makes sense. My hope is that someday we'll know for sure whether the conference is entirely online or in-person, and we can simply go back to using the standard theme/template. In the meantime, the _includes/conference-description.html is a clean way to keep things organized.

The program chairs have asked to remove edit links in an effort to keep the site professional looking, so I took them out.

We will definitely stick to using the remote/theme going forward. The pandemic will make planning for this AISTATS unique, so breaking the mold may occasionally be required to reflect various uncertainties. I'll check on the changes I made to dates.html. I recall having issues with the current remote theme not displaying times (in addition to the date), which we felt was necessary for specific deadlines. The issue may be due to how I populated aistats2021's _config.yml, but if not I can share a solution to display the date+time+TZ where appropriate.

**Comment by lawrennd** [comment]
Thanks Robert! 

That would be great to get a good solution on times going. For that, we can work it out locally and then distribute back into remote theme, it's not something I had time to look at yet, and is more important now for these virtual conferences.
